//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Frontend.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string btn_accept {
            get {
                return ResourceManager.GetString("btn_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string btn_add {
            get {
                return ResourceManager.GetString("btn_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string btn_approve {
            get {
                return ResourceManager.GetString("btn_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btn_back {
            get {
                return ResourceManager.GetString("btn_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE ACTIVE.
        /// </summary>
        public static string btn_change {
            get {
                return ResourceManager.GetString("btn_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        public static string btn_clear {
            get {
                return ResourceManager.GetString("btn_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string btn_delete {
            get {
                return ResourceManager.GetString("btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string btn_download {
            get {
                return ResourceManager.GetString("btn_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT.
        /// </summary>
        public static string btn_export {
            get {
                return ResourceManager.GetString("btn_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string btn_generate {
            get {
                return ResourceManager.GetString("btn_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUICK ADD.
        /// </summary>
        public static string btn_quick_add {
            get {
                return ResourceManager.GetString("btn_quick_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        public static string btn_search {
            get {
                return ResourceManager.GetString("btn_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string btn_submit {
            get {
                return ResourceManager.GetString("btn_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string btn_update {
            get {
                return ResourceManager.GetString("btn_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không có dữ liệu.
        /// </summary>
        public static string DEPARTMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("DEPARTMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time From must be less than Time To.
        /// </summary>
        public static string ERROR_TIMEFROM_TIMETO {
            get {
                return ResourceManager.GetString("ERROR_TIMEFROM_TIMETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during processing.
        /// </summary>
        public static string error400 {
            get {
                return ResourceManager.GetString("error400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login system.
        /// </summary>
        public static string error401 {
            get {
                return ResourceManager.GetString("error401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string errorServer {
            get {
                return ResourceManager.GetString("errorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lbl_add {
            get {
                return ResourceManager.GetString("lbl_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lbl_address {
            get {
                return ResourceManager.GetString("lbl_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add successfully.
        /// </summary>
        public static string lbl_addSuccess {
            get {
                return ResourceManager.GetString("lbl_addSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Successfully.
        /// </summary>
        public static string lbl_approveSuccess {
            get {
                return ResourceManager.GetString("lbl_approveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string lbl_birthday {
            get {
                return ResourceManager.GetString("lbl_birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want to update status?.
        /// </summary>
        public static string lbl_change_message {
            get {
                return ResourceManager.GetString("lbl_change_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update status successfully.
        /// </summary>
        public static string lbl_ChangeSuccess {
            get {
                return ResourceManager.GetString("lbl_ChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Date.
        /// </summary>
        public static string lbl_choose_date {
            get {
                return ResourceManager.GetString("lbl_choose_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose department.
        /// </summary>
        public static string lbl_choose_department {
            get {
                return ResourceManager.GetString("lbl_choose_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose devision.
        /// </summary>
        public static string lbl_choose_division {
            get {
                return ResourceManager.GetString("lbl_choose_division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose line.
        /// </summary>
        public static string lbl_choose_line {
            get {
                return ResourceManager.GetString("lbl_choose_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose line department.
        /// </summary>
        public static string lbl_choose_line_department {
            get {
                return ResourceManager.GetString("lbl_choose_line_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose product.
        /// </summary>
        public static string lbl_choose_product {
            get {
                return ResourceManager.GetString("lbl_choose_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose role.
        /// </summary>
        public static string lbl_choose_role {
            get {
                return ResourceManager.GetString("lbl_choose_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose store.
        /// </summary>
        public static string lbl_choose_store {
            get {
                return ResourceManager.GetString("lbl_choose_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose supplier.
        /// </summary>
        public static string lbl_choose_supplier {
            get {
                return ResourceManager.GetString("lbl_choose_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Time.
        /// </summary>
        public static string lbl_choose_time {
            get {
                return ResourceManager.GetString("lbl_choose_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose time.
        /// </summary>
        public static string lbl_choose_time_frame {
            get {
                return ResourceManager.GetString("lbl_choose_time_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string lbl_code {
            get {
                return ResourceManager.GetString("lbl_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string lbl_command {
            get {
                return ResourceManager.GetString("lbl_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string lbl_contact {
            get {
                return ResourceManager.GetString("lbl_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string lbl_created_date {
            get {
                return ResourceManager.GetString("lbl_created_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string lbl_date {
            get {
                return ResourceManager.GetString("lbl_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string lbl_day {
            get {
                return ResourceManager.GetString("lbl_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want to delete?.
        /// </summary>
        public static string lbl_delete_message {
            get {
                return ResourceManager.GetString("lbl_delete_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successfully.
        /// </summary>
        public static string lbl_deleteSuccess {
            get {
                return ResourceManager.GetString("lbl_deleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Delivered.
        /// </summary>
        public static string lbl_delivered_full {
            get {
                return ResourceManager.GetString("lbl_delivered_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Delivery.
        /// </summary>
        public static string lbl_delivered_not {
            get {
                return ResourceManager.GetString("lbl_delivered_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially Delivered.
        /// </summary>
        public static string lbl_delivered_partialy {
            get {
                return ResourceManager.GetString("lbl_delivered_partialy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Delivery.
        /// </summary>
        public static string lbl_delivered_return {
            get {
                return ResourceManager.GetString("lbl_delivered_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string lbl_department {
            get {
                return ResourceManager.GetString("lbl_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lbl_description {
            get {
                return ResourceManager.GetString("lbl_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string lbl_detail {
            get {
                return ResourceManager.GetString("lbl_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STORE&apos;S INFORMATION.
        /// </summary>
        public static string lbl_detail_store {
            get {
                return ResourceManager.GetString("lbl_detail_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string lbl_division {
            get {
                return ResourceManager.GetString("lbl_division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lbl_edit {
            get {
                return ResourceManager.GetString("lbl_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit successfully.
        /// </summary>
        public static string lbl_editSuccess {
            get {
                return ResourceManager.GetString("lbl_editSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lbl_email {
            get {
                return ResourceManager.GetString("lbl_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalid.
        /// </summary>
        public static string lbl_email_invalid {
            get {
                return ResourceManager.GetString("lbl_email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Store Name.
        /// </summary>
        public static string lbl_enter_store_name {
            get {
                return ResourceManager.GetString("lbl_enter_store_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Supplier Name.
        /// </summary>
        public static string lbl_enter_supplier_name {
            get {
                return ResourceManager.GetString("lbl_enter_supplier_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Supplier No.
        /// </summary>
        public static string lbl_enter_supplier_no {
            get {
                return ResourceManager.GetString("lbl_enter_supplier_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string lbl_error {
            get {
                return ResourceManager.GetString("lbl_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string lbl_fullname {
            get {
                return ResourceManager.GetString("lbl_fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lbl_gender {
            get {
                return ResourceManager.GetString("lbl_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Parameter Infomation.
        /// </summary>
        public static string lbl_header_detail_system_parameter {
            get {
                return ResourceManager.GetString("lbl_header_detail_system_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST ORDER INFORMATION.
        /// </summary>
        public static string lbl_header_order {
            get {
                return ResourceManager.GetString("lbl_header_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string lbl_header_role {
            get {
                return ResourceManager.GetString("lbl_header_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Parameter.
        /// </summary>
        public static string lbl_header_system_parameter {
            get {
                return ResourceManager.GetString("lbl_header_system_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Time Frame.
        /// </summary>
        public static string lbl_header_time_frame {
            get {
                return ResourceManager.GetString("lbl_header_time_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create time frame.
        /// </summary>
        public static string lbl_header_time_frame_add {
            get {
                return ResourceManager.GetString("lbl_header_time_frame_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time frame information.
        /// </summary>
        public static string lbl_header_time_frame_detail {
            get {
                return ResourceManager.GetString("lbl_header_time_frame_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit time frame.
        /// </summary>
        public static string lbl_header_time_frame_edit {
            get {
                return ResourceManager.GetString("lbl_header_time_frame_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        public static string lbl_header_user {
            get {
                return ResourceManager.GetString("lbl_header_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lbl_image {
            get {
                return ResourceManager.GetString("lbl_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng thời gian giữa các khung giờ. Đơn vị phút.
        /// </summary>
        public static string lbl_key_note {
            get {
                return ResourceManager.GetString("lbl_key_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string lbl_line {
            get {
                return ResourceManager.GetString("lbl_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Code.
        /// </summary>
        public static string lbl_line_code {
            get {
                return ResourceManager.GetString("lbl_line_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lbl_login {
            get {
                return ResourceManager.GetString("lbl_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login To Your Account.
        /// </summary>
        public static string lbl_loginTitle {
            get {
                return ResourceManager.GetString("lbl_loginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string lbl_logout {
            get {
                return ResourceManager.GetString("lbl_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string lbl_minute {
            get {
                return ResourceManager.GetString("lbl_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code :.
        /// </summary>
        public static string lbl_modal_qr_code {
            get {
                return ResourceManager.GetString("lbl_modal_qr_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Success.
        /// </summary>
        public static string lbl_modal_qr_tile {
            get {
                return ResourceManager.GetString("lbl_modal_qr_tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified At.
        /// </summary>
        public static string lbl_modifyat {
            get {
                return ResourceManager.GetString("lbl_modifyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string lbl_modifyby {
            get {
                return ResourceManager.GetString("lbl_modifyby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string lbl_month {
            get {
                return ResourceManager.GetString("lbl_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lbl_name {
            get {
                return ResourceManager.GetString("lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string lbl_no {
            get {
                return ResourceManager.GetString("lbl_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string lbl_note {
            get {
                return ResourceManager.GetString("lbl_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string lbl_noti {
            get {
                return ResourceManager.GetString("lbl_noti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string lbl_number {
            get {
                return ResourceManager.GetString("lbl_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lbl_param_name {
            get {
                return ResourceManager.GetString("lbl_param_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string lbl_param_note {
            get {
                return ResourceManager.GetString("lbl_param_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string lbl_param_value {
            get {
                return ResourceManager.GetString("lbl_param_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lbl_password {
            get {
                return ResourceManager.GetString("lbl_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password contain  lowercase letter, uppercase letter,  numeric digit , unlimit special character.
        /// </summary>
        public static string lbl_password_validate {
            get {
                return ResourceManager.GetString("lbl_password_validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lbl_phone {
            get {
                return ResourceManager.GetString("lbl_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number invalid.
        /// </summary>
        public static string lbl_phone_invalid {
            get {
                return ResourceManager.GetString("lbl_phone_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Store&apos;s Phone Number.
        /// </summary>
        public static string lbl_place_phone {
            get {
                return ResourceManager.GetString("lbl_place_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Store&apos;s Description.
        /// </summary>
        public static string lbl_placeholder_address {
            get {
                return ResourceManager.GetString("lbl_placeholder_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Store&apos;s Email.
        /// </summary>
        public static string lbl_placeholder_email {
            get {
                return ResourceManager.GetString("lbl_placeholder_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Store&apos;s Code.
        /// </summary>
        public static string lbl_placeholder_storecode {
            get {
                return ResourceManager.GetString("lbl_placeholder_storecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Store&apos;s Name.
        /// </summary>
        public static string lbl_placeholder_storename {
            get {
                return ResourceManager.GetString("lbl_placeholder_storename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string lbl_product_code {
            get {
                return ResourceManager.GetString("lbl_product_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string lbl_product_name {
            get {
                return ResourceManager.GetString("lbl_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string lbl_product_note {
            get {
                return ResourceManager.GetString("lbl_product_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Order.
        /// </summary>
        public static string lbl_product_total_order {
            get {
                return ResourceManager.GetString("lbl_product_total_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Refuse.
        /// </summary>
        public static string lbl_product_total_refuse {
            get {
                return ResourceManager.GetString("lbl_product_total_refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string lbl_product_upload_image {
            get {
                return ResourceManager.GetString("lbl_product_upload_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Receipt.
        /// </summary>
        public static string lbl_receipt_full {
            get {
                return ResourceManager.GetString("lbl_receipt_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed Receipt.
        /// </summary>
        public static string lbl_receipt_missing {
            get {
                return ResourceManager.GetString("lbl_receipt_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Receipt.
        /// </summary>
        public static string lbl_receipt_return {
            get {
                return ResourceManager.GetString("lbl_receipt_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse Successfully.
        /// </summary>
        public static string lbl_refuseSuccess {
            get {
                return ResourceManager.GetString("lbl_refuseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string lbl_register_approve {
            get {
                return ResourceManager.GetString("lbl_register_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in.
        /// </summary>
        public static string lbl_register_check_in {
            get {
                return ResourceManager.GetString("lbl_register_check_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-out.
        /// </summary>
        public static string lbl_register_check_out {
            get {
                return ResourceManager.GetString("lbl_register_check_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        public static string lbl_register_delivery_date {
            get {
                return ResourceManager.GetString("lbl_register_delivery_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Information.
        /// </summary>
        public static string lbl_register_delivery_information {
            get {
                return ResourceManager.GetString("lbl_register_delivery_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Delivery Date.
        /// </summary>
        public static string lbl_register_delivery_invoice_date {
            get {
                return ResourceManager.GetString("lbl_register_delivery_invoice_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Item Quantity.
        /// </summary>
        public static string lbl_register_delivery_item_quantity {
            get {
                return ResourceManager.GetString("lbl_register_delivery_item_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Order Code.
        /// </summary>
        public static string lbl_register_delivery_order_code {
            get {
                return ResourceManager.GetString("lbl_register_delivery_order_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Order Quantity.
        /// </summary>
        public static string lbl_register_delivery_order_quantity {
            get {
                return ResourceManager.GetString("lbl_register_delivery_order_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Registration Date.
        /// </summary>
        public static string lbl_register_delivery_registration_date {
            get {
                return ResourceManager.GetString("lbl_register_delivery_registration_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Registration Time.
        /// </summary>
        public static string lbl_register_delivery_registration_time {
            get {
                return ResourceManager.GetString("lbl_register_delivery_registration_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Status.
        /// </summary>
        public static string lbl_register_delivery_status {
            get {
                return ResourceManager.GetString("lbl_register_delivery_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Vehicle.
        /// </summary>
        public static string lbl_register_delivery_vehicle {
            get {
                return ResourceManager.GetString("lbl_register_delivery_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string lbl_register_department {
            get {
                return ResourceManager.GetString("lbl_register_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code.
        /// </summary>
        public static string lbl_register_department_code {
            get {
                return ResourceManager.GetString("lbl_register_department_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery information.
        /// </summary>
        public static string lbl_register_detail {
            get {
                return ResourceManager.GetString("lbl_register_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage supplier delivery status.
        /// </summary>
        public static string lbl_register_detail_status {
            get {
                return ResourceManager.GetString("lbl_register_detail_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMND/Driver&apos;s license.
        /// </summary>
        public static string lbl_register_driver_cmnd {
            get {
                return ResourceManager.GetString("lbl_register_driver_cmnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Email.
        /// </summary>
        public static string lbl_register_driver_emergency_email {
            get {
                return ResourceManager.GetString("lbl_register_driver_emergency_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Phone.
        /// </summary>
        public static string lbl_register_driver_emergency_phone {
            get {
                return ResourceManager.GetString("lbl_register_driver_emergency_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plates.
        /// </summary>
        public static string lbl_register_driver_license_plates {
            get {
                return ResourceManager.GetString("lbl_register_driver_license_plates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Driver&apos;s Name.
        /// </summary>
        public static string lbl_register_driver_name {
            get {
                return ResourceManager.GetString("lbl_register_driver_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORM ĐẶT LỊCH GIAO HÀNG.
        /// </summary>
        public static string lbl_register_form {
            get {
                return ResourceManager.GetString("lbl_register_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        public static string lbl_register_invoice_number {
            get {
                return ResourceManager.GetString("lbl_register_invoice_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string lbl_register_line {
            get {
                return ResourceManager.GetString("lbl_register_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss Invoice Number.
        /// </summary>
        public static string lbl_register_miss_invoice {
            get {
                return ResourceManager.GetString("lbl_register_miss_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Link.
        /// </summary>
        public static string lbl_register_public_link {
            get {
                return ResourceManager.GetString("lbl_register_public_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string lbl_register_reason {
            get {
                return ResourceManager.GetString("lbl_register_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt No.
        /// </summary>
        public static string lbl_register_receipt_no {
            get {
                return ResourceManager.GetString("lbl_register_receipt_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Status.
        /// </summary>
        public static string lbl_register_receipt_status {
            get {
                return ResourceManager.GetString("lbl_register_receipt_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Time.
        /// </summary>
        public static string lbl_register_receive_time {
            get {
                return ResourceManager.GetString("lbl_register_receive_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department&apos;s name.
        /// </summary>
        public static string lbl_register_receiver_department_name {
            get {
                return ResourceManager.GetString("lbl_register_receiver_department_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver&apos;s Name.
        /// </summary>
        public static string lbl_register_receiver_name {
            get {
                return ResourceManager.GetString("lbl_register_receiver_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse.
        /// </summary>
        public static string lbl_register_refuse {
            get {
                return ResourceManager.GetString("lbl_register_refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse Apart.
        /// </summary>
        public static string lbl_register_refuse_apart {
            get {
                return ResourceManager.GetString("lbl_register_refuse_apart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse Full.
        /// </summary>
        public static string lbl_register_refuse_full {
            get {
                return ResourceManager.GetString("lbl_register_refuse_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Invoice Number.
        /// </summary>
        public static string lbl_register_return_invoice {
            get {
                return ResourceManager.GetString("lbl_register_return_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status information.
        /// </summary>
        public static string lbl_register_status_information {
            get {
                return ResourceManager.GetString("lbl_register_status_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string lbl_register_store {
            get {
                return ResourceManager.GetString("lbl_register_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lbl_register_supplier_email {
            get {
                return ResourceManager.GetString("lbl_register_supplier_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        public static string lbl_register_supplier_name {
            get {
                return ResourceManager.GetString("lbl_register_supplier_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier No.
        /// </summary>
        public static string lbl_register_supplier_no {
            get {
                return ResourceManager.GetString("lbl_register_supplier_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Phone.
        /// </summary>
        public static string lbl_register_supplier_phone {
            get {
                return ResourceManager.GetString("lbl_register_supplier_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this field is required.
        /// </summary>
        public static string lbl_required {
            get {
                return ResourceManager.GetString("lbl_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATE RESULT.
        /// </summary>
        public static string lbl_result_generate {
            get {
                return ResourceManager.GetString("lbl_result_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETURN INFORMATION.
        /// </summary>
        public static string lbl_return_search_title {
            get {
                return ResourceManager.GetString("lbl_return_search_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER RETURN INFORMATION.
        /// </summary>
        public static string lbl_return_title {
            get {
                return ResourceManager.GetString("lbl_return_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Successfully.
        /// </summary>
        public static string lbl_returnSuccess {
            get {
                return ResourceManager.GetString("lbl_returnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string lbl_role {
            get {
                return ResourceManager.GetString("lbl_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new role.
        /// </summary>
        public static string lbl_role_add_header {
            get {
                return ResourceManager.GetString("lbl_role_add_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role&apos;s information.
        /// </summary>
        public static string lbl_role_detail_header {
            get {
                return ResourceManager.GetString("lbl_role_detail_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role.
        /// </summary>
        public static string lbl_role_edit_header {
            get {
                return ResourceManager.GetString("lbl_role_edit_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lbl_search {
            get {
                return ResourceManager.GetString("lbl_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID.
        /// </summary>
        public static string lbl_staffid {
            get {
                return ResourceManager.GetString("lbl_staffid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lbl_status {
            get {
                return ResourceManager.GetString("lbl_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lbl_status_active {
            get {
                return ResourceManager.GetString("lbl_status_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lbl_status_delete {
            get {
                return ResourceManager.GetString("lbl_status_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string lbl_status_inactive {
            get {
                return ResourceManager.GetString("lbl_status_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string lbl_store {
            get {
                return ResourceManager.GetString("lbl_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Management.
        /// </summary>
        public static string lbl_store_managerment {
            get {
                return ResourceManager.GetString("lbl_store_managerment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string lbl_store_title {
            get {
                return ResourceManager.GetString("lbl_store_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Code.
        /// </summary>
        public static string lbl_storecode {
            get {
                return ResourceManager.GetString("lbl_storecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        public static string lbl_storename {
            get {
                return ResourceManager.GetString("lbl_storename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string lbl_supplier {
            get {
                return ResourceManager.GetString("lbl_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        public static string lbl_supplier_name {
            get {
                return ResourceManager.GetString("lbl_supplier_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier No.
        /// </summary>
        public static string lbl_supplier_no {
            get {
                return ResourceManager.GetString("lbl_supplier_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string lbl_time {
            get {
                return ResourceManager.GetString("lbl_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Frame.
        /// </summary>
        public static string lbl_time_frame {
            get {
                return ResourceManager.GetString("lbl_time_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time From.
        /// </summary>
        public static string lbl_time_frame_from {
            get {
                return ResourceManager.GetString("lbl_time_frame_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Frame.
        /// </summary>
        public static string lbl_time_frame_title {
            get {
                return ResourceManager.GetString("lbl_time_frame_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time To.
        /// </summary>
        public static string lbl_time_frame_to {
            get {
                return ResourceManager.GetString("lbl_time_frame_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time out.
        /// </summary>
        public static string lbl_timeout {
            get {
                return ResourceManager.GetString("lbl_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user.
        /// </summary>
        public static string lbl_user_add_header {
            get {
                return ResourceManager.GetString("lbl_user_add_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account&apos;s information.
        /// </summary>
        public static string lbl_user_detail_header {
            get {
                return ResourceManager.GetString("lbl_user_detail_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string lbl_user_edit_header {
            get {
                return ResourceManager.GetString("lbl_user_edit_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string lbl_user_profile_header {
            get {
                return ResourceManager.GetString("lbl_user_profile_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string lbl_username {
            get {
                return ResourceManager.GetString("lbl_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string lbl_warning {
            get {
                return ResourceManager.GetString("lbl_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Location.
        /// </summary>
        public static string lbl_working_location {
            get {
                return ResourceManager.GetString("lbl_working_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string lbl_year {
            get {
                return ResourceManager.GetString("lbl_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngành hàng không có dữ liệu.
        /// </summary>
        public static string LINE_NOT_FOUND {
            get {
                return ResourceManager.GetString("LINE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max amount .
        /// </summary>
        public static string ORDER_MAX_AMOUNT {
            get {
                return ResourceManager.GetString("ORDER_MAX_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found.
        /// </summary>
        public static string ORDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ORDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        public static string PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store is exists.
        /// </summary>
        public static string STORE_IS_EXIST {
            get {
                return ResourceManager.GetString("STORE_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier not found.
        /// </summary>
        public static string SUPPLIER_NOT_FOUND {
            get {
                return ResourceManager.GetString("SUPPLIER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemParam not found.
        /// </summary>
        public static string SYSTEM_PARAMETER_NOT_FOUND {
            get {
                return ResourceManager.GetString("SYSTEM_PARAMETER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Frame is exist.
        /// </summary>
        public static string TIMEFRAME_IS_EXIST {
            get {
                return ResourceManager.GetString("TIMEFRAME_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeFrame not Found.
        /// </summary>
        public static string TIMEFRAME_NOT_FOUND {
            get {
                return ResourceManager.GetString("TIMEFRAME_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffId/Username is exist.
        /// </summary>
        public static string USER_IS_EXIST {
            get {
                return ResourceManager.GetString("USER_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/password not correct.
        /// </summary>
        public static string USER_NOT_CORRECT {
            get {
                return ResourceManager.GetString("USER_NOT_CORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be larger than {1}.
        /// </summary>
        public static string VALIDATE_TIME {
            get {
                return ResourceManager.GetString("VALIDATE_TIME", resourceCulture);
            }
        }
    }
}
